//REQUEST ACTIONS
export const GET_ITEMS = "GET_ITEMS";
export const SEND_ITEMS = "SEND_ITEMS";
export const GET_PAY_METHODS = "GET_PÁY_METHODS";

//CART ACTIONS
export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const ADD_ITEM_QUANTITY = "ADD_ITEM_QUANTITY";
export const REMOVE_ITEM_QUANTITY = "REMOVE_ITEM_QUANTITY";
export const SHOW_CART = "SHOW_CART";

//FILTERS
export const SEND_TO_ITEM_VIEW = "SEND_TO_ITEM_VIEW";

//UI
export const LOADING_HANDLER = "LOADING_HANDLER";

export const SET_SEND_VALUE = "SET_SEND_VALUE";
export const IS_REQUESTING_SEND = "IS_REQUESTING_SEND";
export const SET_CHOOSE_SEND_VALUE = "SET_CHOOSE_SEND_VALUE";

export const CALCULATE_PRICE = "CALCULATE_PRICE";
export const SET_SHOP_HOVER = "SET_SHOP_HOVER";
export const DISMISS_SHOP_HOVER = "DISMISS_SHOP_HOVER";

export const SET_COLOR = "SET_COLOR";

export const SET_ITEM_COLOR = "SET_ITEM_COLOR";

export const SHOW_PREVIEW_MODAL = "SHOW_PREVIEW_MODAL";
export const DISMISS_PREVIEW_MODAL = "DISMISS_PREVIEW_MODAL";

export const SET_PREVIEW_MODAL_IMAGES = "SET_PREVIEW_MODAL_IMAGES ";
export const SET_PREVIEW_MODAL_INFO = "SET_PREVIEW_MODAL_INFO";

export const SET_USER_INFO = "SET_USER_INFO";
export const SET_SEND_TYPE = "SET_SEND_TYPE";

export const SET_SUBMIT = "SET_SUBMIT";
export const DISMISS_SUBMIT = "DISMISS_SUBMIT";

export const SET_MAILING_RESULT = "SET_MAILING_RESULT";
export const SET_TRACKING_RESULT = "SET_TRACKING_RESULT";
export const OPEN_NAV = "OPEN_NAV";
export const CLOSE_NAV = "CLOSE_NAV";

export const OPEN_DETAIL_MDOAL = "OPEN_DETAIL_MDOAL";
export const CLOSE_DETAIL_MDOAL = "CLOSE_DETAIL_MDOAL";

export const OPEN_SIZE_MDOAL = "OPEN_SIZE_MDOAL";
export const CLOSE_SIZE_MDOAL = "CLOSE_SIZE_MDOAL";

export const SET_ERROR = "SET_ERROR";
export const CLEAN_ERROR = "CLEAN_ERROR";
